spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@otus.wsu2f.mongodb.net/bookClub?retryWrites=true&w=majority
      database: bookClub

management:
  endpoints:
    web:
      exposure:
        include: metrics, logfile, health

  endpoint:
    health:
      show-details: always

  health:
    mongo:
      enabled: true

logging:
  file:
    path: target/app.log
