spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
