spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
    rest:
      basePath: /api

management:
  endpoints:
    web:
      exposure:
        include: metrics, logfile, health

  endpoint:
    health:
      show-details: always

  health:
    mongo:
      enabled: true

logging:
  file:
    path: target/app.log

