version: "3"
services:
  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    networks:
      - nw

  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo
      - MONGO_PORT=27017
      - MONGO_DB=library
    depends_on:
      - mongo
    networks:
      - nw
networks:
  nw:
