version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin@otus.wsu2f.mongodb.net/bookClub?retryWrites=true&w=majority
      - MONGO_DB=bookClub
    networks:
      - nw
networks:
  nw: